-- MySQL Script generated by MySQL Workbench
-- 04/25/18 21:08:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Identidad
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Identidad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Identidad` DEFAULT CHARACTER SET utf8 ;
USE `Identidad` ;

-- -----------------------------------------------------
-- Table `Identidad`.`tbl_identidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Identidad`.`tbl_identidades` ;

CREATE TABLE IF NOT EXISTS `Identidad`.`tbl_identidades` (
  `CodigoID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Numero` VARCHAR(45) NOT NULL,
  `Foto` LONGBLOB NOT NULL,
  PRIMARY KEY (`CodigoID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

#DELETE FROM tbl_identidades WHERE CodigoID>=0;

SELECT count(*) FROM tbl_identidades;

SELECT CodigoID,Nombre,Numero,Foto FROM tbl_identidades WHERE CodigoID >= 1;
